"""Character state schema and helpers.

The canonical wizard state lives in ``state.json`` (see ``docs``/``plan``).
This package defines the typed schema, step-key vocabulary (contract K1),
and pure helpers used by storage and the router.
"""

from create_char_passport.state.schema import (
    BaseEmotion,
    BaseOutfit,
    CharacterState,
    EmotionItem,
    Emotions,
    OutfitDetail,
    OutfitEntry,
    OutfitRefs,
    PromptLayers,
    PropEntry,
    PropShot,
    StepRecord,
    blank_state,
    character_id_from_name,
    state_from_dict,
    state_to_dict,
)
from create_char_passport.state.steps import (
    ALL_STATIC_STEPS,
    BASE_EMOTION_STEP,
    DATASET_PREFIX,
    EMOTION_PREFIX,
    OUTFIT_PREFIX,
    PASSPORT_STEPS,
    PROP_PREFIX,
    StepKind,
    classify_step,
    dataset_step,
    emotion_step,
    is_passport_step,
    ordered_step_keys,
    outfit_detail_step,
    outfit_step,
    prop_shot_step,
    slugify,
)

__all__ = [
    "ALL_STATIC_STEPS",
    "BASE_EMOTION_STEP",
    "DATASET_PREFIX",
    "EMOTION_PREFIX",
    "OUTFIT_PREFIX",
    "PASSPORT_STEPS",
    "PROP_PREFIX",
    "BaseEmotion",
    "BaseOutfit",
    "CharacterState",
    "EmotionItem",
    "Emotions",
    "OutfitDetail",
    "OutfitEntry",
    "OutfitRefs",
    "PromptLayers",
    "PropEntry",
    "PropShot",
    "StepKind",
    "StepRecord",
    "blank_state",
    "character_id_from_name",
    "classify_step",
    "dataset_step",
    "emotion_step",
    "is_passport_step",
    "ordered_step_keys",
    "outfit_detail_step",
    "outfit_step",
    "prop_shot_step",
    "slugify",
    "state_from_dict",
    "state_to_dict",
]
